# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

learnLDS <- function(y, u, v, mu, init, niter, tol) {
    .Call(`_LDSreconstruction_learnLDS`, y, u, v, mu, init, niter, tol)
}

