# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implement Kalman smoothing
#'
#' Estimate the hidden state and expected log-likelihood given the observations, exogeneous input and system parameters
#'
#' @param y Observation matrix (may need to be normalized and centered before hand) (q rows, T columns)
#' @param u Input matrix for the state equation (m_u rows, T columns)
#' @param v Input matrix for the output equation (m_v rows, T columns)
#' @param theta A list of system parameters (A, B, C, D, Q, R)'
#' @return A list of fitted elements (X, Y, V, Cov, and lik)
#' @section Note: This code only works on one dimensional state and output at the moment. Therefore, transposing is skipped, and matrix inversion is treated as /, and log(det(Sigma)) is treated as log(Sigma).
NULL

#' Learn LDS model
#'
#' Estimate the hidden state and model parameters given observations and exogeneous inputs
#'
#' @param y Observation matrix (may need to be normalized and centered before hand) (q rows, T columns)
#' @param u Input matrix for the state equation (m_u rows, T columns)
#' @param v Input matrix for the output equation (m_v rows, T columns)
#' @param mu The mean of y (if y was centralized before), to be added back to the prediction
#' @return A list of fitted elements (X, Y, V, Cov, and lik)
#' * X: a matrix of fitted states
#' * Y: a matrix of fitted observation
#' * V: a matrix of covariance of X
#' * Cov: covariance of X_t and X_t-1
#' lik : log-likelihood
#' @section Note: This code only works on one dimensional state and output at the moment. Therefore, transposing is skipped, and matrix inversion is treated as /, and log(det(Sigma)) is treated as log(Sigma).
learnLDS <- function(y, u, v, init, niter, tol) {
    .Call(`_ldsr_learnLDS`, y, u, v, init, niter, tol)
}

