# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implement Kalman smoothing
#'
#' Estimate the hidden state and expected log-likelihood given the observations, exogeneous input and system parameters. This is an internal function and should not be called directly.
#'
#' @param y Observation matrix (may need to be normalized and centered before hand) (q rows, T columns)
#' @param u Input matrix for the state equation (m_u rows, T columns)
#' @param v Input matrix for the output equation (m_v rows, T columns)
#' @param theta A list of system parameters (A, B, C, D, Q, R)'
#' @return A list of fitted elements (X, Y, V, Cov, and lik)
#' @section Note: This code only works on one dimensional state and output at the moment. Therefore, transposing is skipped, and matrix inversion is treated as /, and log(det(Sigma)) is treated as log(Sigma).
Kalman_smoother <- function(y, u, v, theta) {
    .Call(`_ldsr_Kalman_smoother`, y, u, v, theta)
}

#' Maximizing expected likelihood using analytical solution
#'
#' @inheritParams Kalman_smoother
#' @param fit result of a Kalman_smoother
Mstep <- function(y, u, v, fit) {
    .Call(`_ldsr_Mstep`, y, u, v, fit)
}

#' Learn LDS model
#'
#' Estimate the hidden state and model parameters given observations and exogeneous inputs using the EM algorithm. This is the key backend routine of this package.
#'
#' @inheritParams Kalman_smoother
#' @param init A list of initial conditions, each element is a vector of length 4, the initial values for A, B, C and D. The initial values for Q and R are always 1, and mu_1 is 0 and V_1 is 1.
#' @param niter Maximum number of iterations, default 1000
#' @param tol Tolerance for likelihood convergence, default 1e-5. Note that the log-likelihood is normalized
#' @return A list of model results
#' * theta: model parameters (A, B, C, D, Q, R, mu1, V1) resulted from Mstep
#' * fit: results of Estep
#'     - X: a matrix of fitted states
#'     - Y: a matrix of fitted observation
#'     - V: a matrix of covariance of X
#'     - Cov: covariance of X_t and X_t-1
#' * lik : log-likelihood
#' @section Note: This code only works on one dimensional state and output at the moment. Therefore, transposing is skipped, and matrix inversion is treated as /, and log(det(Sigma)) is treated as log(Sigma).
learnLDS <- function(y, u, v, init, niter, tol) {
    .Call(`_ldsr_learnLDS`, y, u, v, init, niter, tol)
}

